language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: guanyilun
  password:
    secure: GWG5k16ShOz7DBr38EqGpozLaxWEkDGMJFbktsDVwyWeg9yURe7kyEdGUfml451BhU2ATYjtYizu0rSQg5JTB+n710gHHVEq26DbT3+ziexgnB/NZ6jxFLSvXvhHQ5BJdaU87XQjdTfD8tj/5qcDhAFUtX6ZFFoCG8oc9rtaffdEqPMNrZUc2//WO+RUoWL+4V6AkpCHGvnVVcCk0yhhDhkK5I8+wijJEGkr1Bk5BmFXq3Hj/zP9B+nmTeJxvXfAsD41xJqNxigI+xJbtBujdyI4sNzfQGhKOuAQGXmMnn2YUGYrqzk4QEW9QGlRTRvTaTmrsMOWCwyTvTn5hSRuZ0xpnAN1NeD/Q9+4XwwJatJUwO+PTDMb5WiKUU8otOUavPdcGqItNwUXpCsOuuGNntmpdMTJ7wAp6tBqiR3tkI9y+86i9LRvsdCNJ6hpZRhDlzPCgyHZJudBWeaSySBpVchNqIDbxKck9SYQineXvIoEAr36Kwl2D6M7ZUEOgrfT2M1OYGiCrfWY72j7P3TaSw/WvWuEl1lvdbYkBJfqoM3unTv3GlNy6cuvpoZB1nut9BGGrFzcE+ClVpffnzDwOy8mAMXZ9C0hSbnzUMFRirZCgOfmDL5r1xVGx5gNyI/IglmH/X7TqK0zWmJ4As0sTY2iGxEAJREaqtnEbghp35I=
  on:
    tags: true
    repo: guanyilun/todloop
    python: 3.6
